[package]
name = "aws-profile-switcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fuzzy_finder = "0.1.2"
home = "0.5.3"
